[package]
name = "xlayer-core"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
serde.workspace = true
hex.workspace = true
tiny-keccak.workspace = true
xlayer-smt = { path = "../smt" }
