[Node]
HTTPHost = "0.0.0.0"
HTTPPort = 8545
HTTPCors = ["*"]
HTTPVirtualHosts = ["*"]
HTTPModules = ["web3", "debug", "eth", "txpool", "net", "engine", "miner", "admin"]
WSHost = "0.0.0.0"
WSPort = 7546
WSOrigins = ["*"]
WSModules = ["debug", "eth", "txpool", "net", "engine"]
AuthAddr = "0.0.0.0"
AuthPort = 8552
AuthVirtualHosts = ["*"]
JWTSecret = "/jwt.txt"

[Node.P2P]
MaxPeers = 30
DiscoveryV5 = true


[Eth]
NetworkId = 196
SyncMode = "full"


[Eth.GPO]
MinSuggestedPriorityFee = 1
