[Node]
HTTPHost = "0.0.0.0"
HTTPPort = 8545
HTTPCors = ["*"]
HTTPVirtualHosts = ["*"]
HTTPModules = ["web3", "debug", "eth", "txpool", "net", "engine", "miner", "admin"]
WSHost = "0.0.0.0"
WSPort = 7546
WSOrigins = ["*"]
WSModules = ["debug", "eth", "txpool", "net", "engine"]
AuthAddr = "0.0.0.0"
AuthPort = 8552
AuthVirtualHosts = ["*"]
JWTSecret = "/jwt.txt"

[Node.P2P]
MaxPeers = 30
DiscoveryV5 = true

StaticNodes = [
  "enode://2104d54a7fbd58a408590035a3628f1e162833c901400d490ccc94de416baf13639ce2dad388b7a5fd43c535468c106b660d42d94451e39b08912005aa4e4195@8.210.181.50:30303"
]

[Eth]
NetworkId = 1952
SyncMode = "full"
[Eth.GPO]
MinSuggestedPriorityFee = 1
