[Node]
HTTPHost = "0.0.0.0"
HTTPPort = 8545
HTTPCors = ["*"]
HTTPVirtualHosts = ["*"]
HTTPModules = ["web3", "debug", "eth", "txpool", "net", "engine", "miner", "admin"]
WSHost = "0.0.0.0"
WSPort = 7546
WSOrigins = ["*"]
WSModules = ["debug", "eth", "txpool", "net", "engine"]
AuthAddr = "0.0.0.0"
AuthPort = 8552
AuthVirtualHosts = ["*"]
JWTSecret = "/jwt.txt"

[Node.P2P]
MaxPeers = 30
DiscoveryV5 = false
StaticNodes = [
  "enode://ef8135659def07b48b54fe2de7d0368e3eaa0a080ef13dde560169357900954be1a1e890b5973a821f9158e512a2da3ff600368f44e18e725a86931eaae5ef64@op-seq-el:30303",
  "enode://d53a3a3ba6a48dba7605b40e1ec448775c98e8def0c8b99b2cc1cc94ac8844ada28e9208934830979cea650362b77c873c7801f52c8590358e5b2b1717172c27@op-seq-el2:30303",
  "enode://7d55f88b368875a905f641bb451f39c6e825f665ccb7134a75c0bae7f9db82c7f01e37004151e61f21562b92b896b7bee2066c735a11ff6ac11a2c055b9fce40@op-seq-el3:30303",
]

[Eth]
SyncMode = "full"

[Eth.TxPool]
GlobalSlots = 500000
GlobalQueue = 100000
AccountSlots = 50000
AccountQueue = 10000

[Eth.XLayer]
EnableInnerTx = false
[Eth.GPO]
MinSuggestedPriorityFee = 1
