[Node]
HTTPHost = "0.0.0.0"
HTTPPort = 8545
HTTPCors = ["*"]
HTTPVirtualHosts = ["*"]
HTTPModules = ["web3", "debug", "eth", "txpool", "net", "engine", "miner", "admin"]
WSHost = "0.0.0.0"
WSPort = 7546
WSOrigins = ["*"]
WSModules = ["debug", "eth", "txpool", "net", "engine"]
AuthAddr = "0.0.0.0"
AuthPort = 8552
AuthVirtualHosts = ["*"]
JWTSecret = "/jwt.txt"

[Node.P2P]
MaxPeers = 30
DiscoveryV5 = true
# we add both geth and reth to static nodes, but only one is live
#  "enode://9adbd6a98a02fd385b96274529ee49bbcf743e1ddb130fa2be21dc5bce27b409d7b1d8c769b36e8721a659b7d2c37f373cb17e73d25f0bc0b58ab263516f8ee3@op-reth-rpc2:30303", 
StaticNodes = [
  "enode://da6f07c5216e51cfab6320ffeebc6e8fadbb8ce32d489c8dedba9f910fa91b82a534ecef67a42202e7beb92313ee9023bd6dd9a9b2548d175baabf3842dc3053@op-geth-rpc:30303", 
]

[Eth]
SyncMode = "full"

[Eth.TxPool]
GlobalSlots = 500000
GlobalQueue = 100000
AccountSlots = 50000
AccountQueue = 10000

[Eth.XLayer]
EnableInnerTx = true
[Eth.GPO]
MinSuggestedPriorityFee = 1
