[package]
name = "node"
version.workspace = true
edition.workspace = true

[dependencies]
xlayer-core.workspace = true
xlayer-smt.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
serde.workspace = true
serde_json.workspace = true
axum.workspace = true
hex.workspace = true
