CONFIG_NAME: devnet
PRESET_BASE: interop
# Genesis
GENESIS_FORK_VERSION: 0x20000089

# Altair
ALTAIR_FORK_EPOCH: 0
ALTAIR_FORK_VERSION: 0x20000090

# Merge
BELLATRIX_FORK_EPOCH: 0
BELLATRIX_FORK_VERSION: 0x20000091
TERMINAL_TOTAL_DIFFICULTY: 0

# Capella
CAPELLA_FORK_EPOCH: 0
CAPELLA_FORK_VERSION: 0x20000092
MAX_WITHDRAWALS_PER_PAYLOAD: 16

# Deneb
DENEB_FORK_EPOCH: 0
DENEB_FORK_VERSION: 0x20000093

# Blob retention configuration
# 7 days = 75600 epochs (75600 × 4 slots × 2 seconds = 604,800s = 7 days)
MIN_EPOCHS_FOR_BLOB_SIDECARS_REQUESTS: 75600

#Electra
ELECTRA_FORK_EPOCH: 0
ELECTRA_FORK_VERSION: 0x15000000
#Fulu
FULU_FORK_EPOCH: 0
FULU_FORK_VERSION: 0x15000001

# Time parameters
SECONDS_PER_SLOT: 2
SLOTS_PER_EPOCH: 4 # change this because of this check https://github.com/OffchainLabs/prysm/blob/92bd211e4dfb583d7d3602e21a48e38f753155d9/beacon-chain/state/state-native/setters_proposer_lookahead.go#L18-L20
MIN_SEED_LOOKAHEAD: 15
MAX_SEED_LOOKAHEAD: 18

# Blob schedule - Enable 21 blobs from epoch 0
BLOB_SCHEDULE:
  - EPOCH: 0
    MAX_BLOBS_PER_BLOCK: 21

# Deposit contract
DEPOSIT_CONTRACT_ADDRESS: 0x4242424242424242424242424242424242424242
